# params.yaml
index_col: 'id'
target_col: 'price'
one_hot_drop: 'if_binary'
loss_function: 'RMSE'
# n_splits: 5
# metrics: ['f1', 'roc_auc']
# n_jobs: -1
# logisticregression_param_C: 1
# logisticregression_param_penalty: 'l2'