# params.yaml
index_col: 'id'
target_col: 'price'
one_hot_drop: 'if_binary'
loss_function: 'RMSE'
n_splits: 5
# В данной задаче стоит добавить метрику neg_mean_absolute_percentage_error, 
# так как нам важна в том числе относительная ошибка в прогнозе цены на недвижимость.
metrics: ['r2', 'neg_mean_squared_error','neg_mean_absolute_percentage_error']
n_jobs: -1